spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:tcp://localhost/~/test"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /response/
      suffix: .html

logging:
  level:
    org.hibernate.type: trace
